apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-to-aks
  labels:
    app: deploy-to-aks
  namespace: namespace-workflow-1687339141742
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-to-aks
  template:
    metadata:
      labels:
        app: deploy-to-aks
    spec:
      containers:
        - name: deploy-to-aks
          image: containerregistryfabulousdrive.azurecr.io/image-workflow-1687339141742:latest
          ports:
            - containerPort: 8080